[tooling]
54.227.231.68

[todo]
44.206.235.238

[nginx]
18.212.71.224 ansible_ssh_user=ubuntu

[db:vars]
ansible_user=ec2-user
ansible_python_interpreter=/usr/bin/python

[db]
35.173.211.137 ansible_ssh_user=ec2-user