[db]
3.86.241.39 ansible_ssh_user='ec2-user'

[lb]
54.226.107.76

[nfs]
174.129.182.47

[webservers]
44.203.5.113
44.206.232.205

[deployments:children]
lb
nfs
webservers

[deployments:vars]
ansible_ssh_user='ubuntu'
ansible_python_interpreter=/usr/bin/python3
