[db]
44.210.122.152 ansible_ssh_user='ec2-user'

[lb]
54.235.42.150

[nfs]
174.129.182.47

[todo]
18.207.186.5 ansible_ssh_user='ec2-user'

[webservers]
44.203.5.113
44.206.232.205

[deployments:children]
lb
nfs
webservers

[deployments:vars]
ansible_ssh_user='ubuntu'
ansible_python_interpreter=/usr/bin/python3
