[tooling]
54.227.231.68

[todo]
44.206.235.238

[nginx]
18.212.71.224 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devum.pem

[db]
3.83.119.223

[db:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/devum.pem
