[db]
3.82.94.175 ansible_ssh_user='ec2-user'

[lb]
54.165.213.230

[nfs]
174.129.182.47

[todo]
184.73.5.164 ansible_ssh_user='ec2-user'

[webservers]
44.203.5.113
44.206.232.205

[deployments:children]
lb
nfs
webservers

[deployments:vars]
ansible_ssh_user='ubuntu'
ansible_python_interpreter=/usr/bin/python3
