[db]
3.84.220.0 ansible_ssh_user='ec2-user'

[lb]
54.165.213.230

[nfs]
174.129.182.47

[todo]
3.92.228.235 ansible_ssh_user='ec2-user'

[webservers]
44.203.5.113
44.206.232.205

[deployments:children]
lb
nfs
webservers

[deployments:vars]
ansible_ssh_user='ubuntu'
ansible_python_interpreter=/usr/bin/python3
