[db]
3.83.119.223 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=~/.ssh/devum.pem

[lb]
54.227.97.100

[nfs]
3.95.192.122

[webservers]
54.197.121.47
18.208.150.127

[deployments:children]
lb
nfs
webservers

[deployments:vars]
ansible_ssh_user='ubuntu'
ansible_ssh_private_key_file=~/.ssh/devum.pem
ansible_python_interpreter=/usr/bin/python3