pipeline {
  agent any

  parameters {
    string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
  }

  stages {
    stage('Initial Cleanup') {
      steps {
        dir("${WORKSPACE}") {
            deleteDir()
        }
      }
    }
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }
  }
}
